Repository Bamdoliro/G, pull requests merged in 2022-11, with the labels that each got.

#147 solve Deploy failed
  .github/workflows/CD.yml
  docker-compose.yml
Labels: 🐞 Bug

#149 제발돼주세요
  .github/workflows/CD.yml
  docker-compose.yml
Labels: 🐞 Bug

#145 Feat/exception
  src/main/java/com/bamdoliro/gati/domain/board/exception/BoardNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/board/exception/LikeOverlapException.java
  src/main/java/com/bamdoliro/gati/domain/board/exception/ReportOverlapException.java
  src/main/java/com/bamdoliro/gati/domain/board/exception/error/BoardErrorProperty.java
  src/main/java/com/bamdoliro/gati/domain/chat/exception/RoomMemberNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/chat/exception/RoomNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/chat/exception/error/ChatErrorProperty.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/AuthorityMismatchException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/BadChangeCommunityLeaderRequestException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/BadPasswordAndCommunityTypeException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/CannotDeleteCommunityException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/CommunityNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/CommunityPasswordMismatchException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/LeaderCannotLeaveCommunityException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/MemberNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/UserNotCommunityMemberException.java
  src/main/java/com/bamdoliro/gati/domain/community/exception/error/CommunityErrorProperty.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/AlreadyJoinException.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/AlreadyRecommendException.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/DdoNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/ExcessOfCapacityException.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/RecommendationNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/ddo/exception/error/DdoErrorProperty.java
  src/main/java/com/bamdoliro/gati/domain/user/exception/PasswordMismatchException.java
  src/main/java/com/bamdoliro/gati/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/bamdoliro/gati/domain/user/exception/UserNotFoundException.java
  src/main/java/com/bamdoliro/gati/domain/user/exception/error/UserErrorProperty.java
  src/main/java/com/bamdoliro/gati/global/error/ErrorResponse.java
  src/main/java/com/bamdoliro/gati/global/error/GatiExceptionHandler.java
  src/main/java/com/bamdoliro/gati/global/error/exception/ErrorCode.java
  src/main/java/com/bamdoliro/gati/global/error/exception/ErrorProperty.java
  src/main/java/com/bamdoliro/gati/global/error/exception/GatiException.java
  src/main/java/com/bamdoliro/gati/global/error/filter/GlobalErrorFilter.java
  src/main/java/com/bamdoliro/gati/global/security/SecurityConfig.java
  src/main/java/com/bamdoliro/gati/global/security/jwt/exception/ExpiredTokenException.java
  src/main/java/com/bamdoliro/gati/global/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/bamdoliro/gati/global/security/jwt/exception/error/JwtErrorProperty.java
  src/main/java/com/bamdoliro/gati/global/security/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/bamdoliro/gati/global/socket/exception/SocketExceptionListener.java
Labels: ⚙️ Setting, 🔨 Refactor

#156 Feat/ddo
  build.gradle
  src/main/java/com/bamdoliro/gati/domain/board/domain/Board.java
  src/main/java/com/bamdoliro/gati/domain/board/domain/BoardLike.java
  src/main/java/com/bamdoliro/gati/domain/board/domain/Report.java
  src/main/java/com/bamdoliro/gati/domain/chat/domain/Message.java
  src/main/java/com/bamdoliro/gati/domain/chat/domain/Room.java
  src/main/java/com/bamdoliro/gati/domain/chat/domain/RoomMember.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/MessageResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/service/MessageService.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/Community.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/Member.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/request/CreateCommunityRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityDetailResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/domain/Ddo.java
  src/main/java/com/bamdoliro/gati/domain/ddo/domain/DdoJoin.java
  src/main/java/com/bamdoliro/gati/domain/ddo/domain/Recommendation.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/DdoController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/RecommendationController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/request/CreateDdoRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/response/DdoDetailResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/response/DdoListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/response/DdoResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/DdoService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/RecommendationService.java
  src/main/java/com/bamdoliro/gati/domain/user/domain/User.java
  src/main/java/com/bamdoliro/gati/global/config/SwaggerConfig.java
  src/main/java/com/bamdoliro/gati/global/security/SecurityConfig.java
  src/main/java/com/bamdoliro/gati/global/socket/auth/SocketConnectController.java
  src/main/java/com/bamdoliro/gati/global/utils/CustomDateTimeFormatter.java
  src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/board/service/LikeServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/chat/service/MessageServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/community/facade/CommunityFacadeTest.java
  src/test/java/com/bamdoliro/gati/domain/community/facade/MemberFacadeTest.java
  src/test/java/com/bamdoliro/gati/domain/community/service/CommunityServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/community/service/MemberServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/facade/DdoFacadeTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/DdoServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/RecommendationServiceTest.java
Labels: 🔨 Refactor, 🏓 CHORE

#160 [Infra/image] 이미지 업로드 & 수정
  build.gradle
  src/main/java/com/bamdoliro/gati/GatiApplication.java
  src/main/java/com/bamdoliro/gati/domain/board/domain/Board.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/request/CreateBoardRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/Community.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/CommunityController.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/request/CreateCommunityRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityDetailResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/service/CommunityService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/domain/Ddo.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/request/CreateDdoRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/image/presentation/ImageController.java
  src/main/java/com/bamdoliro/gati/domain/image/presentation/dto/response/ImageUrlResponse.java
  src/main/java/com/bamdoliro/gati/domain/image/service/ImageUploadService.java
  src/main/java/com/bamdoliro/gati/domain/user/domain/User.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/UserController.java
  src/main/java/com/bamdoliro/gati/domain/user/service/UserService.java
  src/main/java/com/bamdoliro/gati/global/security/SecurityConfig.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/ImageUtil.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/DefaultImg.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/S3Properties.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/config/S3Config.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/EmptyFileException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/SaveFailedException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/TooLongTitleException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/error/ImageErrorProperty.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/facade/S3Facade.java
  src/main/resources/application.yml
  src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
Labels: ⚙️ Setting, ✨ Feature

#166 Chore/api
  src/main/java/com/bamdoliro/gati/domain/board/.gitkeep
  src/main/java/com/bamdoliro/gati/domain/board/presentation/BoardController.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/ReportController.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/response/BoardListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/response/ReportListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/board/service/BoardService.java
  src/main/java/com/bamdoliro/gati/domain/board/service/ReportService.java
  src/main/java/com/bamdoliro/gati/domain/chat/domain/repository/RoomMemberRepository.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/MessageController.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/RoomController.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/MessageListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/MessageResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/RoomListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/RoomResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/service/MessageService.java
  src/main/java/com/bamdoliro/gati/domain/chat/service/RoomService.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/repository/MemberRepository.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/CommunityController.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityDetailResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/service/CommunityService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/DdoController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/DdoJoinController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/response/UserResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/DdoJoinService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/DdoService.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/UserController.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/dto/response/UserListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/dto/response/UserResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/user/service/UserService.java
  src/test/java/com/bamdoliro/gati/domain/community/service/CommunityServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/DdoJoinServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/DdoServiceTest.java
Labels: 🏓 CHORE

#167 Deploy
  .github/workflows/CD.yml
  build.gradle
  src/main/java/com/bamdoliro/gati/GatiApplication.java
  src/main/java/com/bamdoliro/gati/domain/board/.gitkeep
  src/main/java/com/bamdoliro/gati/domain/board/domain/Board.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/BoardController.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/ReportController.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/request/CreateBoardRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/response/BoardListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/board/presentation/dto/response/ReportListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/board/service/BoardService.java
  src/main/java/com/bamdoliro/gati/domain/board/service/ReportService.java
  src/main/java/com/bamdoliro/gati/domain/chat/domain/repository/RoomMemberRepository.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/MessageController.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/RoomController.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/MessageListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/MessageResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/RoomListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/presentation/dto/response/RoomResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/chat/service/MessageService.java
  src/main/java/com/bamdoliro/gati/domain/chat/service/RoomService.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/Community.java
  src/main/java/com/bamdoliro/gati/domain/community/domain/repository/MemberRepository.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/CommunityController.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/request/CreateCommunityRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityDetailResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/presentation/dto/response/CommunityResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/community/service/CommunityService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/domain/Ddo.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/DdoController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/DdoJoinController.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/request/CreateDdoRequestDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/presentation/dto/response/UserResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/DdoJoinService.java
  src/main/java/com/bamdoliro/gati/domain/ddo/service/DdoService.java
  src/main/java/com/bamdoliro/gati/domain/image/presentation/ImageController.java
  src/main/java/com/bamdoliro/gati/domain/image/presentation/dto/response/ImageUrlResponse.java
  src/main/java/com/bamdoliro/gati/domain/image/service/ImageUploadService.java
  src/main/java/com/bamdoliro/gati/domain/user/domain/User.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/UserController.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/dto/response/UserListResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/user/presentation/dto/response/UserResponseDto.java
  src/main/java/com/bamdoliro/gati/domain/user/service/UserService.java
  src/main/java/com/bamdoliro/gati/global/security/SecurityConfig.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/ImageUtil.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/DefaultImg.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/S3Properties.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/config/S3Config.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/EmptyFileException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/SaveFailedException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/TooLongTitleException.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/exception/error/ImageErrorProperty.java
  src/main/java/com/bamdoliro/gati/infrastructure/image/s3/facade/S3Facade.java
  src/main/resources/application.yml
  src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/community/service/CommunityServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/DdoJoinServiceTest.java
  src/test/java/com/bamdoliro/gati/domain/ddo/service/DdoServiceTest.java
Labels: 🌏 Deploy

#169 Hotfix
  .github/workflows/CD.yml
Labels: 🐞 Bug
